### ISSUE TITLE
jQuery is missing as a dependency

### ISSUE THREAD

**Issue by kurtishouser** [sitepoint-editors/webpack-static-site#1]
Both `index.html` and `photos.html` include script tags to load jQuery from the `node_modules` folder

```
<script src="./node_modules/jquery/dist/jquery.min.js"></script>
```

but it's not listed in the `package.json` file.

```
"dependencies": {
    "lightbox2": "^2.9.0",
    "slick-carousel": "^1.6.0"
}
```

**Comment by jameshibbard** [comment]
Yup, well spotted. I'll get this fixed.
